// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace Util
{
		public static class AnimationUtil
		{
			public static void PlayAnimation(SkeletonAnimation skele, int track, string name, bool loop)
			{
				if (skele.AnimationName != name) skele.state.SetAnimation(track, name, loop);
			}
		}
}

