// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

namespace Bolt.Util
{
	public static class ClampUtil
	{
		/// <summary>
		/// Clamp the specified value, between min and max.
		/// </summary>
		/// <param name="value">Value.</param>
		/// <param name="min">Minimum.</param>
		/// <param name="max">Max.</param>
		public static float Clamp(float value, float min, float max)
		{
			if (value > max)
			{
				return max;
			} else if (value < min)
			{
				return min;
			} else {
				return value;
			}
		}
	}
}

