// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
namespace Control
{
	public class ControlButtonButton : IControlButton
	{ 
	
		private string name;
	
		public ControlButtonButton (string name)
		{
			this.name = name;
		}
		
		public bool IsDown()
		{
			return Input.GetButton(name);
		}
		
		public bool JustPressed()
		{
			return Input.GetButtonDown(name);	
		}
		
		public bool JustReleased()
		{	
			return Input.GetButtonUp(name);
		}
		
		public void Update()
		{
		
		}
		
	}
}

