// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
namespace Control
{
	public class ControlAxisMouseButtons : IControlAxis
	{
		
		private int positive;
		private int negative;
	
		public ControlAxisMouseButtons (int positive, int negative)
		{
			this.positive = positive;
			this.negative = negative;
		}
		
		public float GetAxis()
		{
			var pos = Input.GetMouseButton(positive);
			var neg = Input.GetMouseButton(negative);
		
			if ( pos && !neg )
			{
				return 1f;
			} else if ( neg && !pos)
			{
				return -1f;
			} else {
				return 0f;
			}
		}
	}
}
