// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
namespace Control
{
	public class ControlAxisAxis : IControlAxis
	{
		private string axisName;
		private bool invert;
	
		public ControlAxisAxis (string axisName, bool invert)
		{
			this.axisName = axisName;
			this.invert = invert;
		}
		
		public float GetAxis()
		{
			if (invert)
			{
				return Input.GetAxis(axisName) * -1;
			} else {
				return Input.GetAxis(axisName);
			}
		}
	}
}