// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace Bolt.Control
{
	public class ControlButtonAxis : IControlButton
	{
	
		private string name;
		private float min;
		private float max;
		
		private float lastValue = 0;
		
		private bool justPressed = false;
		private bool justReleased = true;
	
		public ControlButtonAxis (string name, float min, float max)
		{
			this.name = name;
			this.min = min;
			this.max = max;
		}
		
		public bool IsDown()
		{
			return IsInRange(Input.GetAxis(name));
		}
		
		public bool JustPressed()
		{
			return justPressed;
		}
		
		public bool JustReleased()
		{
			return justReleased;
		}
		
		private bool IsInRange(float value)
		{
			return ( value >= min ) && ( value <= max );
		}
		
		public void Update()
		{
			var currentValue = Input.GetAxis(name);
			
			justPressed = justReleased = false;
		
			if (IsInRange (currentValue) && !IsInRange(lastValue))
			{
				justPressed = true;
			}
			
			if (!IsInRange (currentValue) && IsInRange(lastValue))
			{
				justReleased = true;
			}
		
			lastValue = currentValue;
		}
	}	
}

